// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comunicacion.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Jugadas struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Jugadas              []int32  `protobuf:"varint,2,rep,packed,name=jugadas,proto3" json:"jugadas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jugadas) Reset()         { *m = Jugadas{} }
func (m *Jugadas) String() string { return proto.CompactTextString(m) }
func (*Jugadas) ProtoMessage()    {}
func (*Jugadas) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{2}
}

func (m *Jugadas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jugadas.Unmarshal(m, b)
}
func (m *Jugadas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jugadas.Marshal(b, m, deterministic)
}
func (m *Jugadas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jugadas.Merge(m, src)
}
func (m *Jugadas) XXX_Size() int {
	return xxx_messageInfo_Jugadas.Size(m)
}
func (m *Jugadas) XXX_DiscardUnknown() {
	xxx_messageInfo_Jugadas.DiscardUnknown(m)
}

var xxx_messageInfo_Jugadas proto.InternalMessageInfo

func (m *Jugadas) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Jugadas) GetJugadas() []int32 {
	if m != nil {
		return m.Jugadas
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "grpc.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "grpc.HelloReply")
	proto.RegisterType((*Jugadas)(nil), "grpc.Jugadas")
}

func init() { proto.RegisterFile("comunicacion.proto", fileDescriptor_5e958f10881bcae0) }

var fileDescriptor_5e958f10881bcae0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x49, 0x6c, 0x8d, 0x0e, 0x56, 0xca, 0x9c, 0x82, 0x78, 0x28, 0x39, 0x48, 0x2f, 0x4d,
	0xa4, 0x22, 0x9e, 0x5b, 0x02, 0x5a, 0xd1, 0x4b, 0x7a, 0xf3, 0x36, 0xd9, 0x0e, 0x71, 0x35, 0xc9,
	0xc6, 0xfd, 0x10, 0xfa, 0x42, 0x3e, 0xa7, 0x34, 0x4d, 0x40, 0xf1, 0x22, 0x3d, 0xed, 0xfe, 0xbf,
	0xe0, 0xc7, 0x00, 0x0a, 0x55, 0xb9, 0x5a, 0x0a, 0x12, 0x52, 0xd5, 0x71, 0xa3, 0x95, 0x55, 0x38,
	0x28, 0x74, 0x23, 0xa2, 0x08, 0xce, 0x1e, 0xb8, 0x2c, 0x55, 0xc6, 0x1f, 0x8e, 0x8d, 0x45, 0x84,
	0x41, 0x4d, 0x15, 0x87, 0xde, 0xc4, 0x9b, 0x9e, 0x66, 0xed, 0x3f, 0xba, 0x02, 0xe8, 0x3a, 0x4d,
	0xb9, 0xc5, 0x10, 0x82, 0x8a, 0x8d, 0xa1, 0xa2, 0x2f, 0xf5, 0x32, 0xba, 0x83, 0xe0, 0xd1, 0x15,
	0xb4, 0x21, 0x83, 0xe7, 0xe0, 0xaf, 0xd2, 0x36, 0x1f, 0x66, 0xfe, 0x2a, 0xc5, 0x4b, 0x08, 0xde,
	0xf6, 0x51, 0xe8, 0x4f, 0x8e, 0xa6, 0xc3, 0xa5, 0x3f, 0xf6, 0xb2, 0xde, 0x9a, 0x7f, 0x79, 0x1d,
	0xc5, 0x9a, 0xf5, 0xa7, 0x14, 0x8c, 0xd7, 0x70, 0xb2, 0xa6, 0x6d, 0x6b, 0x21, 0xc6, 0x3b, 0xd0,
	0xf8, 0x27, 0xe5, 0xc5, 0xf8, 0x97, 0xb7, 0xa3, 0xba, 0x85, 0x51, 0xbf, 0x58, 0x14, 0x24, 0xeb,
	0x7f, 0xce, 0x66, 0x00, 0xf7, 0x6c, 0x7b, 0xea, 0xd1, 0x3e, 0xef, 0xe4, 0xdf, 0xfa, 0xb2, 0x7a,
	0x79, 0x2f, 0xa4, 0x7d, 0x75, 0x79, 0x2c, 0x54, 0x95, 0x3c, 0xeb, 0x45, 0x4d, 0xa2, 0x64, 0xeb,
	0x4c, 0xf2, 0x44, 0xf9, 0x7c, 0x96, 0x4a, 0x63, 0xb5, 0xcc, 0x9d, 0xdc, 0x28, 0x93, 0x34, 0xda,
	0x71, 0x4e, 0x49, 0x7b, 0xec, 0xe4, 0xa0, 0x55, 0x7e, 0xdc, 0x3e, 0x37, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x06, 0x89, 0x51, 0x5e, 0xbf, 0x01, 0x00, 0x00,
}
