// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comunicacion.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Jugador struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	State                int32    `protobuf:"varint,3,opt,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jugador) Reset()         { *m = Jugador{} }
func (m *Jugador) String() string { return proto.CompactTextString(m) }
func (*Jugador) ProtoMessage()    {}
func (*Jugador) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{2}
}

func (m *Jugador) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jugador.Unmarshal(m, b)
}
func (m *Jugador) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jugador.Marshal(b, m, deterministic)
}
func (m *Jugador) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jugador.Merge(m, src)
}
func (m *Jugador) XXX_Size() int {
	return xxx_messageInfo_Jugador.Size(m)
}
func (m *Jugador) XXX_DiscardUnknown() {
	xxx_messageInfo_Jugador.DiscardUnknown(m)
}

var xxx_messageInfo_Jugador proto.InternalMessageInfo

func (m *Jugador) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Jugador) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Jugador) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type Jugadores struct {
	Jugadores            []*Jugador `protobuf:"bytes,1,rep,name=jugadores,proto3" json:"jugadores,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Jugadores) Reset()         { *m = Jugadores{} }
func (m *Jugadores) String() string { return proto.CompactTextString(m) }
func (*Jugadores) ProtoMessage()    {}
func (*Jugadores) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{3}
}

func (m *Jugadores) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jugadores.Unmarshal(m, b)
}
func (m *Jugadores) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jugadores.Marshal(b, m, deterministic)
}
func (m *Jugadores) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jugadores.Merge(m, src)
}
func (m *Jugadores) XXX_Size() int {
	return xxx_messageInfo_Jugadores.Size(m)
}
func (m *Jugadores) XXX_DiscardUnknown() {
	xxx_messageInfo_Jugadores.DiscardUnknown(m)
}

var xxx_messageInfo_Jugadores proto.InternalMessageInfo

func (m *Jugadores) GetJugadores() []*Jugador {
	if m != nil {
		return m.Jugadores
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "grpc.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "grpc.HelloReply")
	proto.RegisterType((*Jugador)(nil), "grpc.Jugador")
	proto.RegisterType((*Jugadores)(nil), "grpc.Jugadores")
}

func init() { proto.RegisterFile("comunicacion.proto", fileDescriptor_5e958f10881bcae0) }

var fileDescriptor_5e958f10881bcae0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4d, 0x4f, 0x83, 0x40,
	0x14, 0x0c, 0xfd, 0xb0, 0xf2, 0x6c, 0xd5, 0x6c, 0x3c, 0x10, 0x4f, 0x84, 0x83, 0x21, 0x31, 0x82,
	0x62, 0x4c, 0xbc, 0x56, 0x4d, 0xb4, 0x46, 0x3d, 0xc0, 0xcd, 0xdb, 0xb2, 0xbc, 0xe0, 0x2a, 0xb0,
	0xb8, 0x1f, 0x26, 0xfd, 0x4b, 0xfe, 0x4a, 0x03, 0x85, 0xb4, 0x8d, 0x17, 0xe3, 0x89, 0x37, 0xc3,
	0xcc, 0x64, 0x26, 0x0b, 0x84, 0x89, 0xd2, 0x54, 0x9c, 0x51, 0xc6, 0x45, 0x15, 0xd4, 0x52, 0x68,
	0x41, 0x46, 0xb9, 0xac, 0x99, 0xe7, 0xc1, 0xf4, 0x01, 0x8b, 0x42, 0xc4, 0xf8, 0x69, 0x50, 0x69,
	0x42, 0x60, 0x54, 0xd1, 0x12, 0x1d, 0xcb, 0xb5, 0x7c, 0x3b, 0x6e, 0x6f, 0xef, 0x04, 0xa0, 0xd3,
	0xd4, 0xc5, 0x92, 0x38, 0x30, 0x29, 0x51, 0x29, 0x9a, 0xf7, 0xa2, 0x1e, 0x7a, 0xb7, 0x30, 0x79,
	0x34, 0x39, 0xcd, 0x84, 0x6c, 0x62, 0x5e, 0x36, 0x62, 0x9a, 0x9b, 0xec, 0xc3, 0x60, 0x91, 0x39,
	0x03, 0xd7, 0xf2, 0xc7, 0xf1, 0x60, 0x91, 0x91, 0x23, 0x18, 0x27, 0x9a, 0x6a, 0x74, 0x86, 0x2d,
	0xb5, 0x02, 0xde, 0x35, 0xd8, 0x5d, 0x08, 0x2a, 0x72, 0x0a, 0xf6, 0x7b, 0x0f, 0x1c, 0xcb, 0x1d,
	0xfa, 0x7b, 0xd1, 0x2c, 0x68, 0x7a, 0x07, 0x9d, 0x26, 0x5e, 0xff, 0x8f, 0xbe, 0xad, 0x6e, 0x4b,
	0x82, 0xf2, 0x8b, 0x33, 0x24, 0xe7, 0xb0, 0x9b, 0xd0, 0x65, 0x4b, 0x11, 0xb2, 0xb2, 0x6d, 0x6e,
	0x3d, 0x3e, 0xdc, 0xe2, 0x9a, 0x6d, 0x57, 0x30, 0xeb, 0x1d, 0xf3, 0x9c, 0xf2, 0xea, 0x8f, 0xb6,
	0x0b, 0x98, 0xde, 0xa3, 0x5e, 0xd7, 0x3e, 0xd8, 0xea, 0x88, 0xea, 0xb7, 0xe5, 0xa6, 0x7c, 0xfd,
	0xc8, 0xb9, 0x7e, 0x33, 0x69, 0xc0, 0x44, 0x19, 0x3e, 0xcb, 0x79, 0x45, 0x59, 0x81, 0xda, 0xa8,
	0xf0, 0x89, 0xa6, 0xd1, 0xd9, 0x1d, 0x57, 0x5a, 0xf2, 0xd4, 0xf0, 0x4c, 0xa8, 0xb0, 0x96, 0x06,
	0x53, 0x1a, 0xb6, 0xcf, 0x16, 0xfe, 0xcb, 0x95, 0xee, 0xb4, 0x9f, 0xcb, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x71, 0x86, 0xc0, 0xa3, 0x09, 0x02, 0x00, 0x00,
}
