// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat/chat.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type Jugada struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Jugador              int32    `protobuf:"varint,2,opt,name=Jugador,proto3" json:"Jugador,omitempty"`
	Carta                int32    `protobuf:"varint,3,opt,name=Carta,proto3" json:"Carta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jugada) Reset()         { *m = Jugada{} }
func (m *Jugada) String() string { return proto.CompactTextString(m) }
func (*Jugada) ProtoMessage()    {}
func (*Jugada) Descriptor() ([]byte, []int) {
	return fileDescriptor_767a49518b351716, []int{0}
}

func (m *Jugada) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jugada.Unmarshal(m, b)
}
func (m *Jugada) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jugada.Marshal(b, m, deterministic)
}
func (m *Jugada) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jugada.Merge(m, src)
}
func (m *Jugada) XXX_Size() int {
	return xxx_messageInfo_Jugada.Size(m)
}
func (m *Jugada) XXX_DiscardUnknown() {
	xxx_messageInfo_Jugada.DiscardUnknown(m)
}

var xxx_messageInfo_Jugada proto.InternalMessageInfo

func (m *Jugada) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Jugada) GetJugador() int32 {
	if m != nil {
		return m.Jugador
	}
	return 0
}

func (m *Jugada) GetCarta() int32 {
	if m != nil {
		return m.Carta
	}
	return 0
}

// The response message containing the greetings
type Recibo struct {
	Estado               int32    `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recibo) Reset()         { *m = Recibo{} }
func (m *Recibo) String() string { return proto.CompactTextString(m) }
func (*Recibo) ProtoMessage()    {}
func (*Recibo) Descriptor() ([]byte, []int) {
	return fileDescriptor_767a49518b351716, []int{1}
}

func (m *Recibo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recibo.Unmarshal(m, b)
}
func (m *Recibo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recibo.Marshal(b, m, deterministic)
}
func (m *Recibo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recibo.Merge(m, src)
}
func (m *Recibo) XXX_Size() int {
	return xxx_messageInfo_Recibo.Size(m)
}
func (m *Recibo) XXX_DiscardUnknown() {
	xxx_messageInfo_Recibo.DiscardUnknown(m)
}

var xxx_messageInfo_Recibo proto.InternalMessageInfo

func (m *Recibo) GetEstado() int32 {
	if m != nil {
		return m.Estado
	}
	return 0
}

func init() {
	proto.RegisterType((*Jugada)(nil), "chat.Jugada")
	proto.RegisterType((*Recibo)(nil), "chat.Recibo")
}

func init() { proto.RegisterFile("chat/chat.proto", fileDescriptor_767a49518b351716) }

var fileDescriptor_767a49518b351716 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x31, 0xcb, 0xc2, 0x30,
	0x10, 0x86, 0xbf, 0xf6, 0xb3, 0x11, 0x8e, 0xaa, 0x10, 0xa4, 0x04, 0xa7, 0xd2, 0xc9, 0x41, 0x52,
	0xd0, 0xd9, 0xc5, 0x2e, 0xd6, 0xb1, 0x6e, 0x6e, 0x69, 0x12, 0x62, 0xa1, 0xf4, 0x4a, 0x8c, 0xfe,
	0x7e, 0x69, 0x1a, 0x97, 0xe4, 0x9e, 0xf7, 0xe0, 0xe1, 0x3d, 0xd8, 0xc8, 0xa7, 0x70, 0xe5, 0xf4,
	0xf0, 0xd1, 0xa2, 0x43, 0xba, 0x98, 0xe6, 0xe2, 0x0a, 0xe4, 0xf6, 0x36, 0x42, 0x09, 0xba, 0x86,
	0xb8, 0x56, 0x2c, 0xca, 0xa3, 0x7d, 0xd2, 0xc4, 0xb5, 0xa2, 0x0c, 0x96, 0x7e, 0x83, 0x96, 0xc5,
	0x3e, 0xfc, 0x21, 0xdd, 0x42, 0x52, 0x09, 0xeb, 0x04, 0xfb, 0xf7, 0xf9, 0x0c, 0x45, 0x0e, 0xa4,
	0xd1, 0xb2, 0x6b, 0x91, 0x66, 0x40, 0xf4, 0xcb, 0x09, 0x85, 0xc1, 0x16, 0xe8, 0x78, 0x86, 0x55,
	0xd5, 0x77, 0x7a, 0x70, 0x77, 0x6d, 0x3f, 0x9d, 0xd4, 0xf4, 0x00, 0x69, 0x70, 0x4e, 0x9f, 0xa5,
	0x29, 0xf7, 0xfd, 0xe6, 0x42, 0xbb, 0x40, 0xb3, 0xb4, 0xf8, 0xbb, 0xb0, 0x47, 0x66, 0x10, 0x4d,
	0xaf, 0xb9, 0xc1, 0x5e, 0x0c, 0x86, 0xa3, 0x35, 0xa5, 0xb1, 0xa3, 0x6c, 0x89, 0xbf, 0xe8, 0xf4,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x15, 0x05, 0x97, 0xb6, 0xe4, 0x00, 0x00, 0x00,
}
