// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = SupportPackageIsVersion7

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	// Sends a greeting
	JugadorJugar(ctx context.Context, in *Jugada, opts ...CallOption) (*Recibo, error)
}

type clientServiceClient struct {
	cc ClientConnInterface
}

func NewClientServiceClient(cc ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) JugadorJugar(ctx context.Context, in *Jugada, opts ...CallOption) (*Recibo, error) {
	out := new(Recibo)
	err := c.cc.Invoke(ctx, "/chat.ClientService/JugadorJugar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility
type ClientServiceServer interface {
	// Sends a greeting
	JugadorJugar(context.Context, *Jugada) (*Recibo, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (UnimplementedClientServiceServer) JugadorJugar(context.Context, *Jugada) (*Recibo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JugadorJugar not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s ServiceRegistrar, srv ClientServiceServer) {
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_JugadorJugar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor UnaryServerInterceptor) (interface{}, error) {
	in := new(Jugada)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).JugadorJugar(ctx, in)
	}
	info := &UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ClientService/JugadorJugar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).JugadorJugar(ctx, req.(*Jugada))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the ServiceDesc for ClientService service.
// It's only intended for direct use with RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = ServiceDesc{
	ServiceName: "chat.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []MethodDesc{
		{
			MethodName: "JugadorJugar",
			Handler:    _ClientService_JugadorJugar_Handler,
		},
	},
	Streams:  []StreamDesc{},
	Metadata: "chat/chat.proto",
}
